DAR.Web/Controllers/LancesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DAR.Business.Models;
using DAR.Business.Interfaces.Repository;
using AutoMapper;
using DAR.Web.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using DAR.Business.Interfaces;
using DAR.Business.Interfaces.Services;
using System;

namespace DAR.Web.Controllers
{
    public class LancesController : BaseController
    {
        private readonly ILanceRepository _lanceRepository;
        private readonly ILanceService _lanceService;
        private readonly IProdutoRepository _produtoRepository;
        private readonly IPessoaRepository _pessoaRepository;
        private readonly IMapper _mapper;


        public LancesController(ILanceRepository lanceRepository,
                                 ILanceService lanceService,
                                 IProdutoRepository produtoRepository,
                                 IPessoaRepository  pessoaRepository,
                                 IMapper mapper,
                                 INotificador notificador) : base(notificador)
        {
            _lanceService = lanceService;
            _lanceRepository = lanceRepository;
            _produtoRepository = produtoRepository;
            _pessoaRepository = pessoaRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<LanceViewModel>>(await _lanceRepository.ObterTodosComInclude()));

        }
        public async Task<IActionResult> BuscaRapida(int id)
        {
            var lances = _mapper.Map<IEnumerable<LanceViewModel>>(await _lanceRepository.ObterTodosComIncludeProdutoId(id));
            return View("Index",lances);
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = _mapper.Map<LanceViewModel>(await _lanceRepository.ObterComInclude(id));
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["PessoaId"] = new SelectList(await _pessoaRepository.ObterListaCombobox(), "Id", "Nome");
            ViewData["ProdutoId"] = new SelectList(await _produtoRepository.ObterListaCombobox(), "Id", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LanceViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var pessoa = _mapper.Map<PessoaViewModel>(await _pessoaRepository.ObterPorId(viewModel.PessoaId));
                var produto = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterPorId(viewModel.ProdutoId));
                decimal maxlance = 0;

                if (viewModel.PessoaId != 0 && viewModel.ProdutoId != 0)
                {                    
                    if (pessoa.Idade < 18)
                    {
                        TempData["errolance"] = "A pessoa precisa ter mais de 18 anos para realizar lances";
                    }
                    else
                    {
                        List<LanceViewModel> atual = _mapper.Map<List<LanceViewModel>>(await _lanceRepository.ObterTodosComIncludeProdutoId(viewModel.ProdutoId));

                        if (atual.Count > 0)
                            maxlance = maiorValor(atual);
                        
                        if (atual.Count == 0 && viewModel.ValorLance <= produto.Valor)                
                            TempData["errolance"] = "O lance para o produto " + produto.Nome + " precisa ser maior que o valor do produto de R$ " + produto.Valor + " (lance inícial).";                        
                        else if (atual.Count > 0 && viewModel.ValorLance <= maxlance)
                            TempData["errolance"] = "O lance para o produto " + produto.Nome + " precisa ser maior que o lance anterior no valor atual R$ " + maxlance;
                        else 
                        { 
                            var entidade = _mapper.Map<Lance>(viewModel);

                            await _lanceService.Adicionar(entidade);

                            if (!OperacaoValida()) return View(viewModel);

                            TempData["lanceok"] = pessoa.Nome + " seu lance foi aceito no valor de R$ " + viewModel.ValorLance + " para o produto " + produto.Nome;

                            return RedirectToAction(nameof(Index));
                        }
                    }
                }
                else
                {
                    TempData["errocombo"] = "Escolha um produto e uma pessoa para confirmar o lance";
                }
            }
            ViewData["PessoaId"] = new SelectList(await _pessoaRepository.ObterListaCombobox(), "Id", "Nome");
            ViewData["ProdutoId"] = new SelectList(await _produtoRepository.ObterListaCombobox(), "Id", "Nome");
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var viewModel = _mapper.Map<LanceViewModel>(await _lanceRepository.ObterComInclude(id));
            if (viewModel == null)
            {
                return NotFound();
            }
            ViewData["PessoaId"] = new SelectList(await _pessoaRepository.ObterListaCombobox(), "Id", "Nome");
            ViewData["ProdutoId"] = new SelectList(await _produtoRepository.ObterListaCombobox(), "Id", "Nome");
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LanceViewModel viewModel)
        {
            if (id != viewModel.Id) return NotFound();

            if (!ModelState.IsValid) return View(viewModel);

            var entidade = _mapper.Map<Lance>(viewModel);

            await _lanceRepository.Atualizar(entidade);

            if (!OperacaoValida()) return View(viewModel);

            ViewData["PessoaId"] = new SelectList(await _pessoaRepository.ObterTodos(), "Id", "Nome");
            ViewData["ProdutoId"] = new SelectList(await _produtoRepository.ObterTodos(), "Id", "Nome");
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var viewModel = _mapper.Map<LanceViewModel>(await _lanceRepository.ObterComInclude(id));
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _lanceService.Remover(id);
            TempData["Sucesso"] = "Lance excluido com sucesso!";
            return RedirectToAction("Index");
        }
        
        public async Task<decimal> LanceAtual(int id)
        {
            return await _lanceRepository.ObterUltimoLanceProdutoId(id);
        }

        private decimal maiorValor(List<LanceViewModel> lista)
        {
            decimal valor = 0;
            foreach(var item in lista)
                if(item.ValorLance > valor)
                    valor = item.ValorLance;
            
            return valor;
        }

    }
}

DAR.Web/Controllers/PessoasController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DAR.Business.Models;
using DAR.Business.Interfaces.Repository;
using AutoMapper;
using DAR.Web.ViewModels;
using DAR.Business.Interfaces;
using DAR.Business.Interfaces.Services;

namespace DAR.Web.Controllers
{
    public class PessoasController : BaseController
    {
        private readonly IPessoaRepository _pessoaRepository;
        private readonly IPessoaService _pessoaService;
        private readonly IMapper _mapper;


        public PessoasController(IPessoaRepository pessoaRepository,
                                 IPessoaService pessoaService,
                                 IMapper mapper,
                                 INotificador notificador) : base(notificador)
        {
            _pessoaRepository = pessoaRepository;
            _pessoaService = pessoaService;
            _mapper = mapper;
        }
      
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<PessoaViewModel>>(await _pessoaRepository.ObterTodosComInclude()));
            
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = _mapper.Map<PessoaViewModel>(await _pessoaRepository.ObterPorId(id));
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PessoaViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Id = 0;

                var entidade = _mapper.Map<Pessoa>(viewModel);

                await _pessoaService.Adicionar(entidade);

                if (!OperacaoValida()) return View(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var viewModel = _mapper.Map<PessoaViewModel>(await _pessoaRepository.ObterPorId(id));
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PessoaViewModel viewModel)
        {
            if (id != viewModel.Id) return NotFound();

            if (!ModelState.IsValid) return View(viewModel);

            var entidade = _mapper.Map<Pessoa>(viewModel);

            await _pessoaService.Atualizar(entidade);

            if (!OperacaoValida()) return View(viewModel);

            return RedirectToAction("Index");           
        }

        public async Task<IActionResult> Delete(int id)
        {
            var viewModel = _mapper.Map<PessoaViewModel>(await _pessoaRepository.ObterPorId(id));
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _pessoaService.Remover(id);
            TempData["Sucesso"] = "Pessoa excluido com sucesso!";
            return RedirectToAction("Index");
        }

    }
}

DAR.Web/Controllers/ProdutosController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DAR.Business.Models;
using DAR.Business.Interfaces.Repository;
using AutoMapper;
using DAR.Web.ViewModels;
using DAR.Business.Interfaces;
using DAR.Business.Interfaces.Services;

namespace DAR.Web.Controllers
{
    public class ProdutosController : BaseController
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly IProdutoService _produtoService;
        private readonly IMapper _mapper;


        public ProdutosController(IProdutoRepository produtoRepository,
                                 IProdutoService produtoService,
                                 IMapper mapper,
                                 INotificador notificador) : base(notificador)
        {
            _produtoRepository = produtoRepository;
            _produtoService = produtoService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(await _produtoRepository.ObterTodosComInclude()));

        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterPorId(id));
            if (viewModel == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProdutoViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                var entidade = _mapper.Map<Produto>(viewModel);

                await _produtoService.Adicionar(entidade);

                if (!OperacaoValida()) return View(viewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var viewModel = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterPorId(id));
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProdutoViewModel viewModel)
        {
            if (id != viewModel.Id) return NotFound();

            if (!ModelState.IsValid) return View(viewModel);

            var entidade = _mapper.Map<Produto>(viewModel);

            await _produtoService.Atualizar(entidade);

            if (!OperacaoValida()) return View(viewModel);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            var viewModel = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterPorId(id));
            if (viewModel == null)
            {
                return NotFound();
            }
            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _produtoService.Remover(id);
            TempData["Sucesso"] = "Produto excluido com sucesso!";
            return RedirectToAction("Index");
        }

    }
}

DAR.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leilão</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
<body>
    <style>
        .navbar {
            background: rgba(0,0,0,0.6);
            color: #e1ffff;
        }

        body {
            margin: 0px;
            padding: 0px;
            background-color: #ebedef;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight:bold; font-size:24px;color:white;">Leilão</a>
                <button class="navbar-toggler bg-white" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Pessoas" asp-action="Index" style="font-weight:bold;">Gerenciamento de Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Produtos" asp-action="Index" style="font-weight:bold;">Gerenciamento de Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="" asp-controller="Lances" asp-action="Index" style="font-weight:bold;">Gerenciamento de Lances</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Teste - <a href="https://www.linkedin.com/in/daniel-ramiro/">desenvolvedor</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>